
CREATE TABLE IF NOT EXISTS zones (
  id serial PRIMARY KEY,
  albion_id VARCHAR ( 25 ) UNIQUE NOT NULL,
  zone_name VARCHAR ( 100 ) NOT NULL,
  tier VARCHAR ( 10 ) NOT NULL,
  zone_type VARCHAR ( 100 ),
  color VARCHAR ( 10 ) NOT NULL
);

CREATE INDEX idx_zone_name_color ON zones (zone_name, color);

INSERT INTO zones (albion_id, zone_name, tier, zone_type, color) VALUES
	('4300', 'Arthur''s Rest', 'I', 'PLAYERCITY_BLACK_NOFURNITURE', 'city'),
	('2009', 'Astolat', 'VI', 'OPENPVP_RED', 'red'),
	('4358', 'Avalanche Incline', 'VIII', 'OPENPVP_BLACK_4', 'black'),
	('4314', 'Avalanche Ravine', 'V', 'OPENPVP_BLACK_4', 'black'),
	('3316', 'Battlebrae Flatland', 'V', 'OPENPVP_BLACK_4', 'black'),
	('3348', 'Battlebrae Grassland', 'VII', 'OPENPVP_BLACK_5', 'black'),
	('3313', 'Battlebrae Lake', 'V', 'OPENPVP_BLACK_4', 'black'),
	('3349', 'Battlebrae Meadow', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('3317', 'Battlebrae Peaks', 'V', 'OPENPVP_BLACK_4', 'black'),
	('3312', 'Battlebrae Plain', 'V', 'OPENPVP_BLACK_5', 'black'),
	('PSG-0051---3', 'Bedrock Passage', 'VI', 'PASSAGE_BLACK', ' '),
	('3249', 'Bellever Tor', 'IV', 'SAFEAREA', 'blue'),
	('1207', 'Birchcopse', 'IV', 'SAFEAREA', 'blue'),
	('3201', 'Birken Fell', 'VI', 'OPENPVP_RED', 'red'),
	('0356', 'Black Monastery', 'VIII', 'OPENPVP_BLACK_6', ' '),
	('3207', 'Blackthorn Quarry', 'IV', 'SAFEAREA', 'blue'),
	('2333', 'Bleachskull Desert', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('2314', 'Bleachskull Steppe', 'V', 'OPENPVP_BLACK_2', 'black'),
	('0212', 'Bonepool Marsh', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('3208', 'Bowscale Fell', 'VI', 'OPENPVP_RED', 'red'),
	('3331', 'Braemore Lowland', 'VI', 'OPENPVP_BLACK_3', 'black'),
	('3309', 'Braemore Upland', 'V', 'OPENPVP_BLACK_2', 'black'),
	('1305', 'Brambleshore Hinterlands', 'V', 'OPENPVP_BLACK_2', 'black'),
	('3209', 'Brent Knoll', 'III', 'SAFEAREA', 'blue'),
	('2000', 'Bridgewatch', 'I', 'PLAYERCITY_SAFEAREA_01', 'city'),
	('4202', 'Bryn Gorge', 'III', 'SAFEAREA', 'blue'),
	('3003', 'Caerleon', 'VII', 'PLAYERCITY_BLACK_ROYAL', 'city'),
	('4213', 'Cairn Camain', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('4209', 'Cairn Darg', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('4214', 'Cairn Fidair', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('4212', 'Cairn Glascore', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('4205', 'Cairn Gorm', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('0005', 'Camlann', 'VII', 'OPENPVP_RED', 'red'),
	('TNL-045', 'Cases-Ugumlos', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-325', 'Casitos-Alieam', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-255', 'Casitos-Atinaum', 'V', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-227', 'Casitos-Avaelum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-089', 'Casos-Aiagsum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-071', 'Casos-Aximam', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-065', 'Casos-Ayosrom', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-018', 'Casos-Uruxtum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-219', 'Cebitos-Aeaylum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-039', 'Cebos-Avemlum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('1246', 'Cedarcopse', 'IV', 'SAFEAREA', 'blue'),
	('TNL-007', 'Ceres-Iooinum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-238', 'Ceritos-Avulsum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-019', 'Ceros-Aeaylum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-242', 'Cetitos-Aiayrom', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-226', 'Cetitos-Avixnum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-271', 'Cetitos-Aximam', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-008', 'Cetos-Obaelos', 'IV', 'TUNNEL_ROYAL', 'road'),
	('0202', 'Chillhag', 'III', 'SAFEAREA', 'blue'),
	('TNL-245', 'Cieites-Ugumlos', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-284', 'Cieitos-Avioaum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-265', 'Cieitos-Ayosrom', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-208', 'Cieitos-Obaelos', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-350', 'Cieitos-Otatrom', 'VIII', 'TUNNEL_DEEP', 'road'),
	('TNL-145', 'Cieos-Atatlum', 'VIII', 'TUNNEL_HIGH', 'road'),
	('TNL-326', 'Cilitos-Opodam', 'VII', 'TUNNEL_MEDIUM', 'road'),
	('TNL-084', 'Cilos-Avioaum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-093', 'Cilos-Ofailos', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-150', 'Cilos-Otatrom', 'VIII', 'TUNNEL_DEEP', 'road'),
	('2355', 'Citadel of Ash', 'VIII', 'OPENPVP_BLACK_3', ' '),
	('TNL-293', 'Conitos-Ofailos', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-258', 'Conitos-Oxaeaum', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-218', 'Conitos-Uruxtum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-027', 'Conos-Avaelum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-239', 'Coritos-Avemlum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-042', 'Coros-Aiayrom', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-125', 'Coros-Alieam', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-055', 'Coros-Atinaum', 'V', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-002', 'Coues-Exakrom', 'IV', 'TUNNEL_ROYAL', 'road'),
	('PSG-0002', 'Cougar Den', 'V', 'PASSAGE_RED', ' '),
	('TNL-081', 'Couos-Ayayaum', 'VI', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-126', 'Couos-Opodam', 'VII', 'TUNNEL_MEDIUM', 'road'),
	('2202', 'Cracked Earth', 'III', 'SAFEAREA', 'blue'),
	('PSG-0048---1', 'Craglight Cavern', 'VI', 'PASSAGE_BLACK', ' '),
	('4211', 'Creag Garr', 'VI', 'OPENPVP_RED', 'red'),
	('4216', 'Creag Morr', 'VI', 'OPENPVP_RED', 'red'),
	('3212', 'Croker Hill', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('4203', 'Crose Gorge', 'III', 'SAFEAREA', 'blue'),
	('PSG-0038---2', 'Crosscut Skip', 'V', 'PASSAGE_BLACK', ' '),
	('TNL-202', 'Curites-Exakrom', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-281', 'Curitos-Ayayaum', 'VI', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('0213', 'Curlew Fen', 'IV', 'SAFEAREA', 'blue'),
	('TNL-038', 'Curos-Avulsum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-207', 'Cuyites-Iooinum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-289', 'Cynitos-Aiagsum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-345', 'Cynitos-Atatlum', 'VIII', 'TUNNEL_HIGH', 'road'),
	('TNL-026', 'Cynos-Avixnum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-058', 'Cynos-Oxaeaum', 'V', 'TUNNEL_LOW', 'road'),
	('2360', 'Daemonium Keep', 'VIII', 'OPENPVP_BLACK_3', ' '),
	('1358', 'Darkbough Snag', 'VIII', 'OPENPVP_BLACK_6', 'black'),
	('PSG-0039---2', 'Darkseep Core', 'V', 'PASSAGE_BLACK', ' '),
	('PSG-0042---2', 'Darkstone Drift', 'VI', 'PASSAGE_BLACK', ' '),
	('1312', 'Deadpine Forest', 'V', 'OPENPVP_BLACK_6', 'black'),
	('2204', 'Deadvein Gully', 'VI', 'OPENPVP_RED', 'red'),
	('PSG-0052---2', 'Deathcap Channel', 'VI', 'PASSAGE_BLACK', ' '),
	('PSG-0053---2', 'Deathcreep Adit', 'VI', 'PASSAGE_BLACK', ' '),
	('0359', 'Deathreach Priory', 'VIII', 'OPENPVP_BLACK_3', ' '),
	('0347', 'Deathwisp Bog', 'VII', 'OPENPVP_BLACK_6', 'black'),
	('0346', 'Deathwisp Sink', 'VII', 'OPENPVP_BLACK_5', 'black'),
	('1343', 'Deepwood Copse', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('1306', 'Deepwood Dell', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1327', 'Deepwood Gorge', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('1340', 'Deepwood Pines', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('0209', 'Dewleaf Fen', 'IV', 'SAFEAREA', 'blue'),
	('1334', 'Driftwood Glen', 'VI', 'OPENPVP_BLACK_4', 'black'),
	('1348', 'Driftwood Hollow', 'VII', 'OPENPVP_BLACK_5', 'black'),
	('1321', 'Driftwood Vale', 'V', 'OPENPVP_BLACK_5', 'black'),
	('PSG-0053---1', 'Driprock Tunnel', 'VI', 'PASSAGE_BLACK', ' '),
	('0308', 'Drownfield Course', 'V', 'OPENPVP_BLACK_2', 'black'),
	('0313', 'Drownfield Fen', 'V', 'OPENPVP_BLACK_5', 'black'),
	('0310', 'Drownfield Mire', 'V', 'OPENPVP_BLACK_3', 'black'),
	('0340', 'Drownfield Quag', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('0332', 'Drownfield Rut', 'VI', 'OPENPVP_BLACK_5', 'black'),
	('0355', 'Drownfield Sink', 'VIII', 'OPENPVP_BLACK_6', 'black'),
	('0329', 'Drownfield Slough', 'VI', 'OPENPVP_BLACK_4', 'black'),
	('0328', 'Drownfield Wetland', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('2341', 'Drybasin Oasis', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('2308', 'Drybasin Riverbed', 'V', 'OPENPVP_BLACK_3', 'black'),
	('2328', 'Drytop Pillars', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('2327', 'Drytop Riverbed', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('2347', 'Dryvein Confluence', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('2315', 'Dryvein Cross', 'V', 'OPENPVP_BLACK_3', 'black'),
	('2345', 'Dryvein End', 'VII', 'OPENPVP_BLACK_5', 'black'),
	('2334', 'Dryvein Oasis', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('2319', 'Dryvein Plain', 'V', 'OPENPVP_BLACK_2', 'black'),
	('2313', 'Dryvein Riverbed', 'V', 'OPENPVP_BLACK_4', 'black'),
	('2332', 'Dryvein Steppe', 'VI', 'OPENPVP_BLACK_4', 'black'),
	('2207', 'Drywater Meadow', 'IV', 'SAFEAREA', 'blue'),
	('0206', 'Dusklight Fen', 'IV', 'SAFEAREA', 'blue'),
	('1357', 'Eldersleep', 'VIII', 'OPENPVP_BLACK_6', ' '),
	('3204', 'Eldon Hill', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('PSG-0051---4', 'Everglow Deep', 'VI', 'PASSAGE_BLACK', ' '),
	('4307', 'Everwinter Crossing', 'V', 'OPENPVP_BLACK_2', 'black'),
	('4340', 'Everwinter Expanse', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('4341', 'Everwinter Gap', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('4325', 'Everwinter Gorge', 'VI', 'OPENPVP_BLACK_3', 'black'),
	('4353', 'Everwinter Incline', 'VIII', 'OPENPVP_BLACK_4', 'black'),
	('4337', 'Everwinter Passage', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('4322', 'Everwinter Peak', 'VI', 'OPENPVP_BLACK_3', 'black'),
	('4323', 'Everwinter Plain', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('4321', 'Everwinter Reach', 'V', 'OPENPVP_BLACK_1', 'black'),
	('4310', 'Everwinter Shores', 'V', 'OPENPVP_BLACK_2', 'black'),
	('1356', 'Eye of the Forest', 'VIII', 'OPENPVP_BLACK_4', ' '),
	('2325', 'Farshore Bay', 'V', 'OPENPVP_BLACK_1', 'black'),
	('2353', 'Farshore Cape', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('2351', 'Farshore Drylands', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('2320', 'Farshore Esker', 'V', 'OPENPVP_BLACK_3', 'black'),
	('2336', 'Farshore Heath', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('2338', 'Farshore Lagoon', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('TNL-328', 'Fasites-Azazsum', 'VII', 'TUNNEL_DEEP', 'road'),
	('TNL-323', 'Fasitos-Atezsum', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-336', 'Fasitos-Oleraum', 'VIII', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-342', 'Fasitos-Oyuctum', 'VIII', 'TUNNEL_MEDIUM', 'road'),
	('TNL-073', 'Fasos-Ayiotum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-330', 'Febites-Opavun', 'VII', 'TUNNEL_DEEP', 'road'),
	('TNL-140', 'Febos-Acalun', 'VIII', 'TUNNEL_LOW', 'road'),
	('TNL-331', 'Ferites-Ohohtum', 'VII', 'TUNNEL_DEEP', 'road'),
	('TNL-260', 'Feritos-Enomaum', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-297', 'Feritos-Osinsum', 'VI', 'TUNNEL_MEDIUM', 'road'),
	('1215', 'Ferndell', 'IV', 'SAFEAREA', 'blue'),
	('TNL-142', 'Feros-Oyuctum', 'VIII', 'TUNNEL_MEDIUM', 'road'),
	('TNL-047', 'Fetos-Aiaylos', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-131', 'Fiees-Ohohtum', 'VII', 'TUNNEL_DEEP', 'road'),
	('TNL-246', 'Fieites-Unavtum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-137', 'Fieos-Aiuttum', 'VIII', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-123', 'Fieos-Atezsum', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-128', 'Files-Azazsum', 'VII', 'TUNNEL_DEEP', 'road'),
	('TNL-301', 'Filites-Izohun', 'VI', 'TUNNEL_DEEP', 'road'),
	('TNL-344', 'Filitos-Uzazlum', 'VIII', 'TUNNEL_MEDIUM', 'road'),
	('TNL-138', 'Filos-Abalam', 'VIII', 'TUNNEL_LOW', 'road'),
	('4333', 'Firesink Caldera', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('4349', 'Firesink Trench', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('TNL-295', 'Firitos-Alodrom', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-117', 'Firos-Aiavam', 'VII', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-060', 'Firos-Enomaum', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-096', 'Firos-Ezatam', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-097', 'Firos-Osinsum', 'VI', 'TUNNEL_MEDIUM', 'road'),
	('4354', 'Flammog Desolation', 'VIII', 'OPENPVP_BLACK_4', 'black'),
	('4319', 'Flammog Fork', 'V', 'OPENPVP_BLACK_5', 'black'),
	('4330', 'Flammog Valley', 'VI', 'OPENPVP_BLACK_5', 'black'),
	('3305', 'Flatrock Cliffs', 'V', 'OPENPVP_BLACK_2', 'black'),
	('3328', 'Flatrock Plateau', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('4339', 'Floatshoal Bight', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('4327', 'Floatshoal Fissure', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('4313', 'Floatshoal Floe', 'V', 'OPENPVP_BLACK_3', 'black'),
	('TNL-130', 'Fones-Opavun', 'VII', 'TUNNEL_DEEP', 'road'),
	('TNL-251', 'Fonitos-Amaurom', 'V', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-085', 'Fonos-Aiugsum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-136', 'Fonos-Oleraum', 'VIII', 'TUNNEL_BLACK_HIGH', 'road'),
	('PSG-0007', 'Forest Burrow', 'VII', 'PASSAGE_RED', ' '),
	('1006', 'Forest Cross', 'II', 'STARTINGCITY', 'city'),
	('TNL-247', 'Foritos-Aiaylos', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-032', 'Foros-Egoisum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-144', 'Foros-Uzazlum', 'VIII', 'TUNNEL_MEDIUM', 'road'),
	('4000', 'Fort Sterling', 'I', 'PLAYERCITY_SAFEAREA_02', 'city'),
	('TNL-063', 'Foues-Aeaosum', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-337', 'Fouitos-Aiuttum', 'VIII', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-048', 'Fouos-Agosaum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-051', 'Fouos-Amaurom', 'V', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('2214', 'Fractured Ground', 'III', 'SAFEAREA', 'blue'),
	('4316', 'Frostbite Chasm', 'V', 'OPENPVP_BLACK_2', 'black'),
	('4335', 'Frostbite Mountain', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('4324', 'Frostpeak Ascent', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('4306', 'Frostpeak Vista', 'V', 'OPENPVP_BLACK_1', 'black'),
	('4347', 'Frostseep Crevasse', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('4320', 'Frostseep Ravine', 'V', 'OPENPVP_BLACK_2', 'black'),
	('4336', 'Frostspring Passage', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('4351', 'Frostspring Vulcano', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('TNL-317', 'Furitos-Aiavam', 'VII', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-101', 'Fuyes-Izohun', 'VI', 'TUNNEL_DEEP', 'road'),
	('TNL-340', 'Fuyitos-Acalun', 'VIII', 'TUNNEL_LOW', 'road'),
	('TNL-273', 'Fuyitos-Ayiotum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-046', 'Fynes-Unavtum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-263', 'Fynites-Aeaosum', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-338', 'Fynitos-Abalam', 'VIII', 'TUNNEL_LOW', 'road'),
	('TNL-248', 'Fynitos-Agosaum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-285', 'Fynitos-Aiugsum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-232', 'Fynitos-Egoisum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-296', 'Fynitos-Ezatam', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-095', 'Fynos-Alodrom', 'VI', 'TUNNEL_LOW', 'road'),
	('1310', 'Giantweald Copse', 'V', 'OPENPVP_BLACK_4', 'black'),
	('1308', 'Giantweald Dale', 'V', 'OPENPVP_BLACK_2', 'black'),
	('1341', 'Giantweald Edge', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('1344', 'Giantweald Glade', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('1331', 'Giantweald Roots', 'VI', 'OPENPVP_BLACK_4', 'black'),
	('1328', 'Giantweald Woods', 'VI', 'OPENPVP_BLACK_3', 'black'),
	('4332', 'Glacierbreak Summit', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('4329', 'Glacierfall Canyon', 'VI', 'OPENPVP_BLACK_6', 'black'),
	('4343', 'Glacierfall Cross', 'VII', 'OPENPVP_BLACK_5', 'black'),
	('4356', 'Glacierfall Fissure', 'VIII', 'OPENPVP_BLACK_6', 'black'),
	('4355', 'Glacierfall Pass', 'VIII', 'OPENPVP_BLACK_5', 'black'),
	('4312', 'Glacierfall Passage', 'V', 'OPENPVP_BLACK_2', 'black'),
	('4344', 'Glacierfall Valley', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('PSG-0054---2', 'Gleamstone Deep', 'VI', 'PASSAGE_BLACK', ' '),
	('PSG-0052---3', 'Glowmire Grotto', 'VI', 'PASSAGE_BLACK', ' '),
	('3215', 'Goffers Knoll', 'III', 'SAFEAREA', 'blue'),
	('3323', 'Gravemound Brim', 'V', 'OPENPVP_BLACK_2', 'black'),
	('3352', 'Gravemound Cliffs', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('3324', 'Gravemound Hills', 'V', 'OPENPVP_BLACK_3', 'black'),
	('3351', 'Gravemound Knoll', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('3337', 'Gravemound Slope', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('1352', 'Greenhollow Copse', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('1324', 'Greenhollow Vale', 'V', 'OPENPVP_BLACK_3', 'black'),
	('1355', 'Greenshore Bay', 'VIII', 'OPENPVP_BLACK_2', 'black'),
	('1307', 'Greenshore Peninsula', 'V', 'OPENPVP_BLACK_2', 'black'),
	('3205', 'Gutras Hill', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('4210', 'Gwan Gorge', 'III', 'SAFEAREA', 'blue'),
	('3214', 'Haldon Tor', 'IV', 'SAFEAREA', 'blue'),
	('TNL-277', 'Hasitos-Avaolum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-236', 'Hasitos-Umayaum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-033', 'Hasos-Agoitum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-072', 'Hasos-Ayousum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-040', 'Hasos-Inayaum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-031', 'Hasos-Iuimaum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-079', 'Hasos-Osuorom', 'VI', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('3206', 'Haytor', 'IV', 'SAFEAREA', 'blue'),
	('TNL-062', 'Hebes-Ouaylos', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-261', 'Hebites-Exemrom', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-346', 'Hebitos-Atontum', 'VIII', 'TUNNEL_HIGH', 'road'),
	('TNL-024', 'Hebos-Ulamsum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-243', 'Heritos-Exozlos', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-249', 'Heritos-Eyoztum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-240', 'Heritos-Inayaum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-118', 'Heros-Atoyam', 'VII', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-225', 'Hetitos-Iuaerom', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-091', 'Hieos-Aiigaum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-077', 'Hieos-Avaolum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('1205', 'Highbole Glen', 'VI', 'OPENPVP_RED', 'red'),
	('3002', 'Highland Cross', 'II', 'STARTINGCITY', 'city'),
	('3319', 'Highstone Grassland', 'V', 'OPENPVP_BLACK_2', 'black'),
	('3357', 'Highstone Loch', 'VIII', 'OPENPVP_BLACK_4', 'black'),
	('3311', 'Highstone Meadow', 'V', 'OPENPVP_BLACK_4', 'black'),
	('3346', 'Highstone Mound', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('3315', 'Highstone Plains', 'V', 'OPENPVP_BLACK_3', 'black'),
	('3347', 'Highstone Plateau', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('1333', 'Hightree Borderlands', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('1336', 'Hightree Cliffs', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('1317', 'Hightree Dale', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1322', 'Hightree Enclave', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1320', 'Hightree Glade', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1347', 'Hightree Hillock', 'VII', 'OPENPVP_BLACK_1', 'black'),
	('1345', 'Hightree Isle', 'VII', 'OPENPVP_BLACK_1', 'black'),
	('1316', 'Hightree Lake', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1335', 'Hightree Levee', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('1332', 'Hightree Pass', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('1302', 'Hightree Portal East', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1303', 'Hightree Portal North', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1304', 'Hightree Portal West', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1313', 'Hightree Steep', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1319', 'Hightree Strand', 'V', 'OPENPVP_BLACK_1', 'black'),
	('TNL-148', 'Hiles-Izizaum', 'VIII', 'TUNNEL_DEEP', 'road'),
	('TNL-230', 'Hilites-Ugumtum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-291', 'Hilitos-Aiigaum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-279', 'Hilitos-Osuorom', 'VI', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-043', 'Hiros-Exozlos', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-025', 'Hiros-Iuaerom', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-348', 'Honites-Izizaum', 'VIII', 'TUNNEL_DEEP', 'road'),
	('TNL-206', 'Honitos-Uxeulum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-122', 'Honos-Oyezam', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-036', 'Honos-Umayaum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('1214', 'Hornbeam Wood', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('TNL-127', 'Horos-Ohenlum', 'VII', 'TUNNEL_HIGH', 'road'),
	('TNL-030', 'Hures-Ugumtum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-300', 'Hurites-Ieatun', 'VI', 'TUNNEL_DEEP', 'road'),
	('TNL-262', 'Hurites-Ouaylos', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-231', 'Huritos-Iuimaum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-223', 'Huritos-Oiaelos', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-146', 'Huros-Atontum', 'VIII', 'TUNNEL_HIGH', 'road'),
	('TNL-037', 'Huyes-Ogozlum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-233', 'Huyitos-Agoitum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-327', 'Huyitos-Ohenlum', 'VII', 'TUNNEL_HIGH', 'road'),
	('TNL-049', 'Huyos-Eyoztum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-006', 'Huyos-Uxeulum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-061', 'Hynes-Exemrom', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-100', 'Hynes-Ieatun', 'VI', 'TUNNEL_DEEP', 'road'),
	('TNL-237', 'Hynites-Ogozlum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-318', 'Hynitos-Atoyam', 'VII', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-272', 'Hynitos-Ayousum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-322', 'Hynitos-Oyezam', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-224', 'Hynitos-Ulamsum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-023', 'Hynos-Oiaelos', 'V', 'TUNNEL_ROYAL', 'road'),
	('4342', 'Iceburn Cliffs', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('4318', 'Iceburn Firth', 'V', 'OPENPVP_BLACK_6', 'black'),
	('4328', 'Iceburn Peaks', 'VI', 'OPENPVP_BLACK_4', 'black'),
	('4346', 'Iceburn Tundra', 'VII', 'OPENPVP_BLACK_6', 'black'),
	('1007', 'Inis Mon', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('2201', 'Kindlegrass Steppe', 'VI', 'OPENPVP_RED', 'red'),
	('1201', 'Larchroad', 'III', 'SAFEAREA', 'blue'),
	('2209', 'Lazygrass Plain', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('3203', 'Lewsdon Hill', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('0336', 'Longfen Arms', 'VI', 'OPENPVP_BLACK_3', 'black'),
	('0322', 'Longfen Marsh', 'V', 'OPENPVP_BLACK_4', 'black'),
	('0352', 'Longfen Veins', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('2212', 'Longmarch Meadow', 'IV', 'SAFEAREA', 'blue'),
	('1209', 'Longtimber Glen', 'VI', 'OPENPVP_RED', 'red'),
	('PSG-0051---2', 'Lurkers'' Hollow', 'VI', 'PASSAGE_BLACK', ' '),
	('1000', 'Lymhurst', 'I', 'PLAYERCITY_SAFEAREA_02', 'city'),
	('4215', 'Malag Crevasse', 'VI', 'OPENPVP_RED', 'red'),
	('3202', 'Mardale', 'VI', 'OPENPVP_RED', 'red'),
	('3004', 'Martlock', 'I', 'PLAYERCITY_SAFEAREA_01', 'city'),
	('3210', 'Mase Knoll', 'III', 'SAFEAREA', 'blue'),
	('4208', 'Mawar Gorge', 'IV', 'SAFEAREA', 'blue'),
	('0307', 'Meltwater Bog', 'V', 'OPENPVP_BLACK_3', 'black'),
	('0354', 'Meltwater Channel', 'VIII', 'OPENPVP_BLACK_3', 'black'),
	('0325', 'Meltwater Delta', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('0338', 'Meltwater Sump', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('1012', 'Merlyn''s Rest', 'I', 'PLAYERCITY_BLACK_NOFURNITURE', 'city'),
	('PSG-0050---1', 'Middlemurk Path', 'VI', 'PASSAGE_BLACK', ' '),
	('0008', 'Morgana''s Rest', 'I', 'PLAYERCITY_BLACK_NOFURNITURE', 'city'),
	('4006', 'Mountain Cross', 'II', 'STARTINGCITY', 'city'),
	('0337', 'Mudfoot Mounds', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('0323', 'Mudfoot Sump', 'V', 'OPENPVP_BLACK_1', 'black'),
	('PSG-0045---1', 'Mudrock Burrow', 'VI', 'PASSAGE_BLACK', ' '),
	('4345', 'Munten Fell', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('4315', 'Munten Rise', 'V', 'OPENPVP_BLACK_1', 'black'),
	('4331', 'Munten Tundra', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('3306', 'Murdergulch Cross', 'V', 'OPENPVP_BLACK_4', 'black'),
	('3354', 'Murdergulch Divide', 'VIII', 'OPENPVP_BLACK_5', 'black'),
	('3307', 'Murdergulch Gap', 'V', 'OPENPVP_BLACK_6', 'black'),
	('3355', 'Murdergulch Ravine', 'VIII', 'OPENPVP_BLACK_6', 'black'),
	('3342', 'Murdergulch Trail', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('1210', 'Murkweald', 'VII', 'OPENPVP_RED', 'red'),
	('PSG-0004---1', 'Nightbloom Track', 'VI', 'PASSAGE_BLACK', ' '),
	('0207', 'Nightcreak Marsh', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('2326', 'Northstrand Beach', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('2305', 'Northstrand Dunes', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1204', 'Oakcopse', 'IV', 'SAFEAREA', 'blue'),
	('TNL-201', 'Oasitos-Aoeuam', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-021', 'Oasos-Eraerom', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-017', 'Oasos-Uromlum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-221', 'Oebitos-Eraerom', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-254', 'Oebitos-Oyozam', 'V', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-012', 'Oebos-Ixakaum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-324', 'Oeritos-Ecunsum', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-268', 'Oeritos-Oyexlos', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-103', 'Oetos-Ofailos', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-068', 'Oetos-Oyexlos', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-212', 'Oieitos-Ixakaum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-009', 'Oieos-Umiutum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-116', 'Oires-Oloblum', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-280', 'Oiritos-Eramtum', 'VI', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-133', 'Oiros-Alaiam', 'VIII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-209', 'Oonitos-Umiutum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-099', 'Ooros-Ataltum', 'VI', 'TUNNEL_HIGH', 'road'),
	('TNL-124', 'Ooros-Ecunsum', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-333', 'Oouitos-Alaiam', 'VIII', 'TUNNEL_BLACK_LOW', 'road'),
	('PSG-0006', 'Ore Adit', 'VII', 'PASSAGE_RED', ' '),
	('TNL-029', 'Oures-Araosum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-299', 'Ouritos-Ataltum', 'VI', 'TUNNEL_HIGH', 'road'),
	('TNL-303', 'Ouritos-Ofailos', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-001', 'Ouyos-Aoeuam', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-229', 'Oynites-Araosum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-316', 'Oynites-Oloblum', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-217', 'Oynitos-Uromlum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-080', 'Oynos-Eramtum', 'VI', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-054', 'Oynos-Oyozam', 'V', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('2331', 'Parchsand Cliffs', 'VI', 'OPENPVP_BLACK_4', 'black'),
	('2359', 'Parchsand Drought', 'VIII', 'OPENPVP_BLACK_5', 'black'),
	('2206', 'Parchthroat Plain', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('TNL-016', 'Pasos-Avosam', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-074', 'Pebos-Avosrom', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('4201', 'Pen Garn', 'IV', 'SAFEAREA', 'blue'),
	('4207', 'Pen Gent', 'IV', 'SAFEAREA', 'blue'),
	('4204', 'Pen Kerrig', 'IV', 'SAFEAREA', 'blue'),
	('4249', 'Pen Uchaf', 'IV', 'SAFEAREA', 'blue'),
	('TNL-216', 'Peritos-Avosam', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-321', 'Peritos-Oconun', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-110', 'Peros-Aiataum', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-203', 'Petitos-Amayam', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-274', 'Petitos-Avosrom', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-119', 'Petos-Aietam', 'VII', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-141', 'Pieos-Eterrom', 'VIII', 'TUNNEL_LOW', 'road'),
	('TNL-111', 'Pieos-Ofairom', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-341', 'Pilitos-Eterrom', 'VIII', 'TUNNEL_LOW', 'road'),
	('TNL-250', 'Pirites-Unatam', 'V', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-305', 'Piritos-Ofavam', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-343', 'Piritos-Opabrom', 'VIII', 'TUNNEL_MEDIUM', 'road'),
	('TNL-292', 'Ponitos-Aiayrom', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-092', 'Poros-Aiayrom', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-121', 'Poros-Oconun', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-050', 'Poues-Unatam', 'V', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-311', 'Pouitos-Ofairom', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('2215', 'Prospector''s Hope', 'III', 'SAFEAREA', 'blue'),
	('TNL-004', 'Pures-Ouozlum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-003', 'Puros-Amayam', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-105', 'Puros-Ofavam', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-310', 'Puyitos-Aiataum', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-204', 'Pynites-Ouozlum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-319', 'Pynitos-Aietam', 'VII', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-143', 'Pynos-Opabrom', 'VIII', 'TUNNEL_MEDIUM', 'road'),
	('TNL-171', 'Qiient-Al-Nusom', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-163', 'Qiient-Al-Odesum', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-176', 'Qiient-Al-Qinsis', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-166', 'Qiient-Al-Tersas', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-170', 'Qiient-Al-Viesis', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-164', 'Qiient-Al-Vynsis', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-172', 'Qiient-Et-Nusas', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-173', 'Qiient-Et-Odetis', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-369', 'Qiient-Et-Qinsum', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-168', 'Qiient-Et-Tertum', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-361', 'Qiient-In-Nutis', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-174', 'Qiient-In-Odetum', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-376', 'Qiient-In-Qinsis', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-359', 'Qiient-In-Tersom', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-370', 'Qiient-In-Viesis', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-362', 'Qiient-In-Vyntum', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-161', 'Qiient-Nutis', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-374', 'Qiient-Oc-Odetum', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-160', 'Qiient-Odesas', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-371', 'Qiient-Qi-Nusom', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-360', 'Qiient-Qi-Odesas', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-366', 'Qiient-Qi-Tersas', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-364', 'Qiient-Qi-Vynsis', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-169', 'Qiient-Qinsum', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-373', 'Qiient-Sa-Odetis', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-372', 'Qiient-Si-Nusas', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-363', 'Qiient-Si-Odesum', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-368', 'Qiient-Si-Tertum', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-159', 'Qiient-Tersom', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-162', 'Qiient-Vyntum', 'V', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-375', 'Qiitun-Al-Duosum', 'V', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-175', 'Qiitun-Duosum', 'V', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-367', 'Qiitun-Et-Vietis', 'V', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-165', 'Qiitun-Et-Vynsom', 'V', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-365', 'Qiitun-Si-Vynsom', 'V', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-167', 'Qiitun-Vietis', 'V', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-158', 'Quaent-Al-Nusis', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-157', 'Quaent-Al-Odesum', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-355', 'Quaent-Al-Qintis', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-352', 'Quaent-Al-Tersis', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-353', 'Quaent-Al-Viesom', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-351', 'Quaent-Al-Vynsum', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-358', 'Quaent-In-Nusis', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-357', 'Quaent-In-Odesum', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-155', 'Quaent-Qintis', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-152', 'Quaent-Tersis', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-153', 'Quaent-Viesom', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-151', 'Quaent-Vynsum', 'IV', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-354', 'Quatun-Et-Nusas', 'IV', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-356', 'Quatun-Et-Odetum', 'IV', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-154', 'Quatun-Nusas', 'IV', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-156', 'Quatun-Odetum', 'IV', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('3345', 'Razorrock Bank', 'VII', 'OPENPVP_BLACK_5', 'black'),
	('3343', 'Razorrock Chasm', 'VII', 'OPENPVP_BLACK_6', 'black'),
	('3332', 'Razorrock Edge', 'VI', 'OPENPVP_BLACK_5', 'black'),
	('3356', 'Razorrock Gulch', 'VIII', 'OPENPVP_BLACK_6', 'black'),
	('3308', 'Razorrock Passage', 'V', 'OPENPVP_BLACK_5', 'black'),
	('3330', 'Razorrock Ravine', 'VI', 'OPENPVP_BLACK_6', 'black'),
	('3310', 'Razorrock Valley', 'V', 'OPENPVP_BLACK_5', 'black'),
	('3344', 'Razorrock Verge', 'VII', 'OPENPVP_BLACK_5', 'black'),
	('1208', 'Redlake', 'III', 'SAFEAREA', 'blue'),
	('3359', 'Redtree Enclave', 'VIII', 'OPENPVP_BLACK_2', 'black'),
	('1318', 'Rivercopse Crossing', 'V', 'OPENPVP_BLACK_5', 'black'),
	('1346', 'Rivercopse Curve', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('1359', 'Rivercopse Fount', 'VIII', 'OPENPVP_BLACK_5', 'black'),
	('1349', 'Rivercopse Path', 'VII', 'OPENPVP_BLACK_5', 'black'),
	('2203', 'Roastcorpse Steppe', 'VI', 'OPENPVP_RED', 'red'),
	('PSG-0001', 'Rock Adit', 'V', 'PASSAGE_RED', ' '),
	('PSG-0003', 'Rock Adit', 'VII', 'PASSAGE_RED', ' '),
	('1203', 'Rowanwood', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('3245', 'Runnel Sink', 'VII', 'OPENPVP_RED', 'red'),
	('0326', 'Runnelvein Bog', 'VI', 'OPENPVP_BLACK_3', 'black'),
	('0341', 'Runnelvein Sink', 'VII', 'OPENPVP_BLACK_5', 'black'),
	('0311', 'Runnelvein Slough', 'V', 'OPENPVP_BLACK_5', 'black'),
	('1202', 'Russerdell', 'IV', 'SAFEAREA', 'blue'),
	('PSG-0004', 'Sabertooth Den', 'VI', 'PASSAGE_RED', ' '),
	('3211', 'Saddle Tor', 'IV', 'SAFEAREA', 'blue'),
	('2358', 'Sandmount Ascent', 'VIII', 'OPENPVP_BLACK_2', 'black'),
	('2349', 'Sandmount Desert', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('2318', 'Sandmount Esker', 'V', 'OPENPVP_BLACK_2', 'black'),
	('2312', 'Sandmount Strand', 'V', 'OPENPVP_BLACK_2', 'black'),
	('2323', 'Sandrift Coast', 'V', 'OPENPVP_BLACK_1', 'black'),
	('2350', 'Sandrift Dunes', 'VII', 'OPENPVP_BLACK_1', 'black'),
	('2337', 'Sandrift Expanse', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('2352', 'Sandrift Fringe', 'VII', 'OPENPVP_BLACK_1', 'black'),
	('2304', 'Sandrift Portal East', 'V', 'OPENPVP_BLACK_1', 'black'),
	('2303', 'Sandrift Portal North', 'V', 'OPENPVP_BLACK_1', 'black'),
	('2302', 'Sandrift Portal West', 'V', 'OPENPVP_BLACK_1', 'black'),
	('2322', 'Sandrift Prairie', 'V', 'OPENPVP_BLACK_1', 'black'),
	('2324', 'Sandrift Shore', 'V', 'OPENPVP_BLACK_1', 'black'),
	('2321', 'Sandrift Steppe', 'V', 'OPENPVP_BLACK_1', 'black'),
	('TNL-088', 'Sases-Aoarsum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-075', 'Sases-Avuotum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-335', 'Sasitos-Oyarlum', 'VIII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-309', 'Sasitos-Ugersum', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-283', 'Sasitos-Umogaum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-129', 'Sasos-Abizaum', 'VII', 'TUNNEL_DEEP', 'road'),
	('TNL-041', 'Sasos-Egeylos', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-056', 'Sasos-Oiozlum', 'V', 'TUNNEL_BLACK_HIGH', 'road'),
	('0353', 'Scuttlesink Marsh', 'VIII', 'OPENPVP_BLACK_3', 'black'),
	('0324', 'Scuttlesink Mouth', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('0306', 'Scuttlesink Pools', 'V', 'OPENPVP_BLACK_2', 'black'),
	('TNL-010', 'Sebos-Avoirom', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-149', 'Sebos-Oyohun', 'VIII', 'TUNNEL_DEEP', 'road'),
	('TNL-109', 'Sebos-Ugersum', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-389', 'Secent-Al-Duosom', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-386', 'Secent-Al-Nutum', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-179', 'Secent-Al-Odetis', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-184', 'Secent-Al-Qinsom', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-187', 'Secent-Al-Tersum', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-381', 'Secent-Al-Viesum', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-189', 'Secent-Duosom', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-182', 'Secent-Et-Odesis', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-190', 'Secent-Et-Qinsas', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-380', 'Secent-Et-Vyntum', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-387', 'Secent-In-Tersum', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-186', 'Secent-Nutum', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-177', 'Secent-Odesom', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-377', 'Secent-Qi-Odesom', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-384', 'Secent-Qi-Qinsom', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-382', 'Secent-Sa-Odesis', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-379', 'Secent-Si-Odetis', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-390', 'Secent-Si-Qinsas', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-181', 'Secent-Viesum', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-180', 'Secent-Vyntum', 'VI', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-185', 'Sectun-Al-Vyntis', 'VI', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-378', 'Sectun-Et-Tersas', 'VI', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-188', 'Sectun-In-Odesis', 'VI', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-383', 'Sectun-In-Qinsom', 'VI', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-385', 'Sectun-In-Vyntis', 'VI', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-388', 'Sectun-Oc-Odesis', 'VI', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-183', 'Sectun-Qinsom', 'VI', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-178', 'Sectun-Tersas', 'VI', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-241', 'Seritos-Egeylos', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-252', 'Seritos-Onaytum', 'V', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-396', 'Setent-Al-Duosas', 'VII', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-199', 'Setent-Al-Qinsum', 'VII', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-391', 'Setent-Al-Vietis', 'VII', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-196', 'Setent-Duosas', 'VII', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-393', 'Setent-Et-Nusum', 'VII', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-397', 'Setent-Et-Qintis', 'VII', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-399', 'Setent-In-Qinsum', 'VII', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-193', 'Setent-Nusum', 'VII', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-197', 'Setent-Qintis', 'VII', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-191', 'Setent-Vietis', 'VII', 'TUNNEL_HIDEOUT', 'road'),
	('TNL-282', 'Setitos-Obobrom', 'VI', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-106', 'Setos-Aiaitum', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-034', 'Setos-Avamsum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-200', 'Settun-Al-Nusis', 'VII', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-198', 'Settun-Al-Odetum', 'VII', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-395', 'Settun-Al-Tersom', 'VII', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-394', 'Settun-Al-Vynsis', 'VII', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-392', 'Settun-Et-Odetum', 'VII', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-400', 'Settun-In-Nusis', 'VII', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-398', 'Settun-In-Odetum', 'VII', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-192', 'Settun-Odetum', 'VII', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-195', 'Settun-Tersom', 'VII', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('TNL-194', 'Settun-Vynsis', 'VII', 'TUNNEL_HIDEOUT_DEEP', 'road'),
	('PSG-0051---1', 'Shale Underway', 'VI', 'PASSAGE_BLACK', ' '),
	('3326', 'Shaleheath Hills', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('3338', 'Shaleheath Steep', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('2205', 'Shiftshadow Expanse', 'VII', 'OPENPVP_RED', 'red'),
	('TNL-112', 'Sieos-Ofugtum', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-329', 'Silitos-Abizaum', 'VII', 'TUNNEL_DEEP', 'road'),
	('TNL-094', 'Silos-Apenlum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-135', 'Silos-Oyarlum', 'VIII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-210', 'Siritos-Avoirom', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-349', 'Siritos-Oyohun', 'VIII', 'TUNNEL_DEEP', 'road'),
	('TNL-082', 'Siros-Obobrom', 'VI', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-132', 'Siros-Ofurlos', 'VIII', 'TUNNEL_BLACK_LOW', 'road'),
	('0315', 'Skullmarsh Lower', 'V', 'OPENPVP_BLACK_1', 'black'),
	('0343', 'Skullmarsh Upper', 'VII', 'OPENPVP_BLACK_1', 'black'),
	('3327', 'Skylake Bridge', 'VI', 'OPENPVP_BLACK_3', 'black'),
	('3339', 'Skylake Hinterlands', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('2307', 'Skysand Plateau', 'V', 'OPENPVP_BLACK_3', 'black'),
	('2340', 'Skysand Ridge', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('2309', 'Slakesands Canyon', 'V', 'OPENPVP_BLACK_2', 'black'),
	('2342', 'Slakesands Mesa', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('0201', 'Sleetwater Basin', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('0214', 'Slimehag', 'III', 'SAFEAREA', 'blue'),
	('2208', 'Slowtree Plain', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('2211', 'Smoothfloor Cleft', 'IV', 'SAFEAREA', 'blue'),
	('PSG-0052---1', 'Smuggler''s Rut', 'VI', 'PASSAGE_BLACK', ' '),
	('2210', 'Snapshaft Trough', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('TNL-286', 'Sonitos-Ayailos', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-306', 'Soritos-Aiaitum', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-294', 'Soritos-Apenlum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-234', 'Soritos-Avamsum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-005', 'Soros-Axaesum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-098', 'Soues-Uzurtum', 'VI', 'TUNNEL_MEDIUM', 'road'),
	('TNL-256', 'Souitos-Oiozlum', 'V', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-108', 'Souos-Availos', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-066', 'Souos-Ososlos', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-083', 'Souos-Umogaum', 'VI', 'TUNNEL_LOW', 'road'),
	('1337', 'Southgrove Copse', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('1314', 'Southgrove Escarp', 'V', 'OPENPVP_BLACK_2', 'black'),
	('1350', 'Southgrove Thicket', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('0211', 'Spectral Sump', 'VI', 'OPENPVP_RED', 'red'),
	('0321', 'Springsump Basin', 'V', 'OPENPVP_BLACK_3', 'black'),
	('0351', 'Springsump Melt', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('0335', 'Springsump Wetland', 'VI', 'OPENPVP_BLACK_3', 'black'),
	('1212', 'Stagbourne', 'III', 'SAFEAREA', 'blue'),
	('PSG-0044---1', 'Stalagmite Adit', 'VI', 'PASSAGE_BLACK', ' '),
	('2213', 'Steelhide Meadow', 'IV', 'SAFEAREA', 'blue'),
	('2002', 'Steppe Cross', 'II', 'STARTINGCITY', 'city'),
	('0205', 'Stinkhag', 'III', 'SAFEAREA', 'blue'),
	('3325', 'Stonelake Fields', 'V', 'OPENPVP_BLACK_1', 'black'),
	('3336', 'Stonelake Hillock', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('3335', 'Stonemouth Bay', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('3314', 'Stonemouth Northbluff', 'V', 'OPENPVP_BLACK_2', 'black'),
	('3358', 'Stonemouth Southbluff', 'VIII', 'OPENPVP_BLACK_3', 'black'),
	('PSG-0042---1', 'Stoneslip Passage', 'VI', 'PASSAGE_BLACK', ' '),
	('STUB-0502', 'STUB-0502', 'V', 'PASSAGE_SAFEAREA', ' '),
	('0208', 'Stumprot Swamp', 'VI', 'OPENPVP_RED', 'red'),
	('2330', 'Sunfang Approach', 'VI', 'OPENPVP_BLACK_5', 'black'),
	('2343', 'Sunfang Cliffs', 'VII', 'OPENPVP_BLACK_6', 'black'),
	('2357', 'Sunfang Dawn', 'VIII', 'OPENPVP_BLACK_5', 'black'),
	('2310', 'Sunfang Ravine', 'V', 'OPENPVP_BLACK_5', 'black'),
	('2344', 'Sunfang Wasteland', 'VII', 'OPENPVP_BLACK_6', 'black'),
	('0358', 'Sunkenbough Spring', 'VIII', 'OPENPVP_BLACK_4', 'black'),
	('0349', 'Sunkenbough Woods', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('2317', 'Sunstrand Delta', 'V', 'OPENPVP_BLACK_1', 'black'),
	('2335', 'Sunstrand Dunes', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('2348', 'Sunstrand Quicksands', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('2316', 'Sunstrand Shoal', 'V', 'OPENPVP_BLACK_3', 'black'),
	('TNL-275', 'Suyites-Avuotum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-298', 'Suyites-Uzurtum', 'VI', 'TUNNEL_MEDIUM', 'road'),
	('TNL-205', 'Suyitos-Axaesum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-312', 'Suyitos-Ofugtum', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-339', 'Suyitos-Oyarlos', 'VIII', 'TUNNEL_LOW', 'road'),
	('TNL-052', 'Suyos-Onaytum', 'V', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('PSG-0005', 'Swamp Burrow', 'VII', 'PASSAGE_RED', ' '),
	('0004', 'Swamp Cross', 'II', 'STARTINGCITY', 'city'),
	('2339', 'Swiftsands Basin', 'VII', 'OPENPVP_BLACK_1', 'black'),
	('2354', 'Swiftsands Chaparral', 'VIII', 'OPENPVP_BLACK_2', 'black'),
	('2306', 'Swiftsands Plain', 'V', 'OPENPVP_BLACK_1', 'black'),
	('TNL-288', 'Synites-Aoarsum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-308', 'Synitos-Availos', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-332', 'Synitos-Ofurlos', 'VIII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-266', 'Synitos-Ososlos', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-086', 'Synos-Ayailos', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-139', 'Synos-Oyarlos', 'VIII', 'TUNNEL_LOW', 'road'),
	('TNL-235', 'Tasitos-Obayam', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-228', 'Tasitos-Ulaurom', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-113', 'Tasos-Iriglos', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-222', 'Tebitos-Igaelum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-314', 'Tebitos-Odoxlum', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-011', 'Teros-Auiusum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-290', 'Tetitos-Ayoslum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-022', 'Tetos-Igaelum', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-028', 'Tetos-Ulaurom', 'V', 'TUNNEL_ROYAL', 'road'),
	('4206', 'Tharcal Fissure', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('CenterCity-DNG-01', 'The Underway', 'VII', 'PASSAGE_RED', ' '),
	('0000', 'Thetford', 'I', 'PLAYERCITY_SAFEAREA_01', 'city'),
	('2346', 'Thirstwater Gully', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('2311', 'Thirstwater Steppe', 'V', 'OPENPVP_BLACK_2', 'black'),
	('2329', 'Thirstwater Waste', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('3340', 'Thunderrock Ascent', 'VII', 'OPENPVP_BLACK_6', 'black'),
	('3353', 'Thunderrock Draw', 'VIII', 'OPENPVP_BLACK_6', 'black'),
	('3329', 'Thunderrock Rapids', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('3341', 'Thunderrock Upland', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('TNL-270', 'Tieitos-Eyexrom', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-244', 'Tieitos-Ouultum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-090', 'Tieos-Ayoslum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-320', 'Tilitos-Ataglos', 'VII', 'TUNNEL_LOW', 'road'),
	('1342', 'Timberscar Copse', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('1309', 'Timberscar Dell', 'V', 'OPENPVP_BLACK_2', 'black'),
	('1354', 'Timberslope Bridge', 'VIII', 'OPENPVP_BLACK_2', 'black'),
	('1326', 'Timberslope Dell', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('1339', 'Timberslope Grove', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('1325', 'Timbertop Dale', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('1353', 'Timbertop Escarp', 'VIII', 'OPENPVP_BLACK_1', 'black'),
	('1338', 'Timbertop Wood', 'VII', 'OPENPVP_BLACK_1', 'black'),
	('TNL-114', 'Tiros-Odoxlum', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-044', 'Tiros-Ouultum', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-304', 'Tonitos-Igurlum', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-307', 'Tonitos-Uxavrom', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-147', 'Tonos-Aboysum', 'VIII', 'TUNNEL_DEEP', 'road'),
	('TNL-035', 'Tonos-Obayam', 'V', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-313', 'Toritos-Iriglos', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-120', 'Touos-Ataglos', 'VII', 'TUNNEL_LOW', 'road'),
	('TNL-013', 'Touos-Uoemtum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-259', 'Turitos-Atatlos', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-213', 'Turitos-Uoemtum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-347', 'Tuyitos-Aboysum', 'VIII', 'TUNNEL_DEEP', 'road'),
	('TNL-211', 'Tuyitos-Auiusum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('0350', 'Twinchannel Narrows', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('TNL-059', 'Tynos-Atatlos', 'V', 'TUNNEL_LOW', 'road'),
	('TNL-070', 'Tynos-Eyexrom', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-104', 'Tynos-Igurlum', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-107', 'Tynos-Uxavrom', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('0357', 'Unhallowed Cloister', 'VIII', 'OPENPVP_BLACK_4', ' '),
	('3213', 'Vixen Tor', 'IV', 'SAFEAREA', 'blue'),
	('2356', 'Wailing Bulwark', 'VIII', 'OPENPVP_BLACK_6', ' '),
	('1330', 'Watchwood Bluffs', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('1315', 'Watchwood Grove', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1329', 'Watchwood Lakeside', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('1311', 'Watchwood Precipice', 'V', 'OPENPVP_BLACK_1', 'black'),
	('1351', 'Westweald Shore', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('1323', 'Westweald Thicket', 'V', 'OPENPVP_BLACK_2', 'black'),
	('0305', 'Wetgrave Bog', 'V', 'OPENPVP_BLACK_2', 'black'),
	('0342', 'Wetgrave Marsh', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('0339', 'Wetgrave Swale', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('4311', 'Whitebank Cross', 'V', 'OPENPVP_BLACK_1', 'black'),
	('4305', 'Whitebank Descent', 'V', 'OPENPVP_BLACK_1', 'black'),
	('4304', 'Whitebank Portal East', 'V', 'OPENPVP_BLACK_1', 'black'),
	('4302', 'Whitebank Portal North', 'V', 'OPENPVP_BLACK_1', 'black'),
	('4303', 'Whitebank Portal South', 'V', 'OPENPVP_BLACK_1', 'black'),
	('4338', 'Whitebank Ridge', 'VII', 'OPENPVP_BLACK_1', 'black'),
	('4309', 'Whitebank Shore', 'V', 'OPENPVP_BLACK_1', 'black'),
	('4308', 'Whitebank Stream', 'V', 'OPENPVP_BLACK_1', 'black'),
	('4326', 'Whitebank Wall', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('PSG-0049---1', 'Whitecap Cave', 'VI', 'PASSAGE_BLACK', ' '),
	('4350', 'Whitecliff Expanse', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('4334', 'Whitecliff Peak', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('4317', 'Whitepeak Ascent', 'V', 'OPENPVP_BLACK_4', 'black'),
	('4348', 'Whitepeak Spring', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('4357', 'Whitepeak Tundra', 'VIII', 'OPENPVP_BLACK_3', 'black'),
	('4359', 'Whitewall Pass', 'VIII', 'OPENPVP_BLACK_4', 'black'),
	('4352', 'Whitewall Ridge', 'VII', 'OPENPVP_BLACK_4', 'black'),
	('0317', 'Widemoor Delta', 'V', 'OPENPVP_BLACK_1', 'black'),
	('0330', 'Widemoor End', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('0316', 'Widemoor Estuary', 'V', 'OPENPVP_BLACK_1', 'black'),
	('0348', 'Widemoor Fen', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('0334', 'Widemoor Flats', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('0327', 'Widemoor Hills', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('0312', 'Widemoor Pool', 'V', 'OPENPVP_BLACK_1', 'black'),
	('0302', 'Widemoor Portal North', 'V', 'OPENPVP_BLACK_1', 'black'),
	('0303', 'Widemoor Portal South', 'V', 'OPENPVP_BLACK_1', 'black'),
	('0304', 'Widemoor Portal West', 'V', 'OPENPVP_BLACK_1', 'black'),
	('0309', 'Widemoor Shore', 'V', 'OPENPVP_BLACK_1', 'black'),
	('0333', 'Widemoor Woods', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('1206', 'Willow Wood', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('0344', 'Willowshade Hills', 'VII', 'OPENPVP_BLACK_2', 'black'),
	('0320', 'Willowshade Icemarsh', 'V', 'OPENPVP_BLACK_3', 'black'),
	('0319', 'Willowshade Lake', 'V', 'OPENPVP_BLACK_3', 'black'),
	('0318', 'Willowshade Mire', 'V', 'OPENPVP_BLACK_2', 'black'),
	('0331', 'Willowshade Pools', 'VI', 'OPENPVP_BLACK_2', 'black'),
	('0345', 'Willowshade Sink', 'VII', 'OPENPVP_BLACK_3', 'black'),
	('0314', 'Willowshade Wetlands', 'V', 'OPENPVP_BLACK_1', 'black'),
	('0203', 'Willowsigh Marsh', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('3318', 'Windgrass Border', 'V', 'OPENPVP_BLACK_1', 'black'),
	('3334', 'Windgrass Coast', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('3333', 'Windgrass Fields', 'VI', 'OPENPVP_BLACK_1', 'black'),
	('3320', 'Windgrass Gully', 'V', 'OPENPVP_BLACK_1', 'black'),
	('3303', 'Windgrass Portal North', 'V', 'OPENPVP_BLACK_1', 'black'),
	('3304', 'Windgrass Portal South', 'V', 'OPENPVP_BLACK_1', 'black'),
	('3302', 'Windgrass Portal West', 'V', 'OPENPVP_BLACK_1', 'black'),
	('3322', 'Windgrass Precipice', 'V', 'OPENPVP_BLACK_1', 'black'),
	('3321', 'Windgrass Rill', 'V', 'OPENPVP_BLACK_1', 'black'),
	('3350', 'Windgrass Terrace', 'VII', 'OPENPVP_BLACK_1', 'black'),
	('0204', 'Windripple Fen', 'IV', 'SAFEAREA', 'blue'),
	('0210', 'Wispwhisper Marsh', 'V', 'OPENPVP_YELLOW', 'yellow'),
	('1213', 'Wyre Forest', 'VI', 'OPENPVP_RED', 'red'),
	('TNL-115', 'Xases-Ataglos', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-076', 'Xases-Oxoulum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-014', 'Xasos-Aeoilos', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-078', 'Xasos-Aoemaum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-053', 'Xasos-Oneulum', 'V', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-257', 'Xebitos-Oyogam', 'V', 'TUNNEL_BLACK_HIGH', 'road'),
	('TNL-067', 'Xebos-Emimsum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-069', 'Xebos-Exostum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-276', 'Xerites-Oxoulum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-267', 'Xetitos-Emimsum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-253', 'Xetitos-Oneulum', 'V', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-102', 'Xetos-Obursum', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-087', 'Xiles-Aiavlum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-278', 'Xilitos-Aoemaum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-064', 'Xilos-Osayam', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-134', 'Xiros-Aiairom', 'VIII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-287', 'Xonites-Aiavlum', 'VI', 'TUNNEL_LOW', 'road'),
	('TNL-334', 'Xoritos-Aiairom', 'VIII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-269', 'Xoritos-Exostum', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-264', 'Xoritos-Osayam', 'VI', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-214', 'Xouitos-Aeoilos', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-215', 'Xouitos-Eyoztum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-020', 'Xouos-Aioblos', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-315', 'Xurites-Ataglos', 'VII', 'TUNNEL_BLACK_MEDIUM', 'road'),
	('TNL-015', 'Xuros-Eyoztum', 'IV', 'TUNNEL_ROYAL', 'road'),
	('TNL-220', 'Xuyitos-Aioblos', 'V', 'TUNNEL_ROYAL', 'road'),
	('TNL-302', 'Xynitos-Obursum', 'VII', 'TUNNEL_BLACK_LOW', 'road'),
	('TNL-057', 'Xynos-Oyogam', 'V', 'TUNNEL_BLACK_HIGH', 'road'),
	('1211', 'Yew Wood', 'V', 'OPENPVP_YELLOW', 'yellow');